/* Generated by build.py — do not edit. */
const VERSION = "ivs-50a8f8850253";
const SHELL = [
  "./",
  "css/main.css",
  "css/marks.css",
  "css/fonts.css",
  "js/main.js",
  "site.webmanifest",
  "assets/fonts/cormorant-garamond-normal-500-latin.woff2",
  "assets/fonts/eb-garamond-italic-400800-latin.woff2",
  "assets/fonts/eb-garamond-normal-400800-latin.woff2",
  "assets/brand/favicon.svg",
  "assets/brand/motif.svg",
  "assets/brand/satyr.svg",
  "assets/brand/share.svg",
  "assets/brand/wordmark-line1.svg",
  "assets/brand/wordmark-line2.svg",
  "assets/brand/wordmark-stacked.svg"
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(VERSION).then((cache) => cache.addAll(SHELL)).then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  // Anything from an older build goes, so a stale stylesheet cannot outlive
  // the markup it was written for.
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== VERSION).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET" || new URL(request.url).origin !== self.location.origin) return;

  // Pages come from the network first: a catalogue that is quietly a week old
  // is worse than one that takes a moment. The cache is the fallback, which is
  // what makes the shop readable underground.
  if (request.mode === "navigate") {
    event.respondWith(
      fetch(request)
        .then((response) => {
          const copy = response.clone();
          caches.open(VERSION).then((cache) => cache.put(request, copy));
          return response;
        })
        .catch(() => caches.match(request).then((hit) => hit || caches.match("./")))
    );
    return;
  }

  // Everything else is versioned by the cache name, so cache first.
  event.respondWith(
    caches.match(request).then((hit) => hit || fetch(request).then((response) => {
      const copy = response.clone();
      caches.open(VERSION).then((cache) => cache.put(request, copy));
      return response;
    }))
  );
});
