#!/usr/bin/env python3
"""Self-host the webfonts.

Self-hosting keeps the Google Fonts IP disclosure out of the privacy story and
removes a third-party request from every page load. Latin subsets only — the
site is English.
"""
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FONTS = ROOT / "assets" / "fonts"
CSS = ROOT / "css" / "fonts.css"

UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)
FAMILIES = {
    "Bodoni Moda": "ital,opsz,wght@0,6..96,400..900;1,6..96,400..900",
    "EB Garamond": "ital,wght@0,400..800;1,400..800",
}
# Latin only. latin-ext carries the Czech diacritics for names and addresses.
KEEP = ("U+0000-00FF", "U+0100-02BA")


def get(url):
    """Shell out to curl — this machine's Python has no CA bundle configured."""
    r = subprocess.run(
        ["curl", "-sSL", "--fail", "-m", "45", "-A", UA, url],
        capture_output=True,
    )
    if r.returncode:
        raise SystemExit(f"fetch failed ({r.returncode}): {url}\n{r.stderr.decode()}")
    return r.stdout


def main():
    FONTS.mkdir(parents=True, exist_ok=True)
    CSS.parent.mkdir(parents=True, exist_ok=True)
    blocks = [
        "/* Self-hosted so no request ever leaves for a font. Generated by",
        "   tools/fetch_fonts.py — do not edit by hand. */",
        "",
    ]
    for family, axes in FAMILIES.items():
        url = (
            "https://fonts.googleapis.com/css2?family="
            + family.replace(" ", "+")
            + ":"
            + axes
            + "&display=swap"
        )
        css = get(url).decode()
        kept = 0
        for face in re.findall(r"@font-face\s*\{[^}]+\}", css):
            rng = re.search(r"unicode-range:\s*([^;]+);", face)
            if not rng or not any(k in rng.group(1) for k in KEEP):
                continue
            src = re.search(r"url\((https://[^)]+\.woff2)\)", face)
            if not src:
                continue
            style = re.search(r"font-style:\s*(\w+)", face).group(1)
            weight = re.search(r"font-weight:\s*([^;]+);", face).group(1).strip()
            slug = family.lower().replace(" ", "-")
            name = f"{slug}-{style}-{'ext' if 'U+0100' in rng.group(1) else 'latin'}.woff2"
            (FONTS / name).write_bytes(get(src.group(1)))
            kb = (FONTS / name).stat().st_size / 1024
            print(f"  {name:38} {kb:6.1f} KB")
            blocks += [
                "@font-face {",
                f"  font-family: '{family}';",
                f"  font-style: {style};",
                f"  font-weight: {weight};",
                "  font-display: swap;",
                f"  src: url('../assets/fonts/{name}') format('woff2');",
                f"  unicode-range: {rng.group(1).strip()};",
                "}",
                "",
            ]
            kept += 1
        print(f"{family}: {kept} faces")
    CSS.write_text("\n".join(blocks))
    print(f"wrote {CSS.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
